### ISSUE TITLE
Want to upload favicon for icon in window

### ISSUE THREAD

**Issue by Mimush** [neo-project/global-blockchain-compliance-hub#64]
I need push access to the repository in order to upload an image. Can you grant me push access or upload this image into the assets folder (https://github.com/neo-project/global-blockchain-compliance-hub/tree/master/assets) please?

File should be named favicon.png if uploaded

![favicon](https://user-images.githubusercontent.com/34467798/35597039-88b84ae0-05ea-11e8-88cf-22acc2ac75ca.png)

**Comment by erikzhang** [comment]
Done.
